<?php
return [
'Previous Locations:' => '以前的位置',
'Key' => '答案',
'English' => '英语',
'Spanish' => '西班牙语',
'Edit Translations' => '编辑翻译',
'Translations' => '翻译',
'Chinese' => '中文',
'Back to Articles' => '回到文章',
'Map Location:' => '地图位置',
'Back to Blog' => '回到博客',
'Add New Post' => '添加新帖子',
'Content Stats' => '内容统计',
'Total Content Pages' => '内容页数',
'Total Photos' => '照片总数',
'Content Photos' => '内容照片',
'Gallery Photos' => '图库照片',
'Featured Photos' => '精选照片',
'Content Pages' => '内容页面',
'Photo Pages' => '照片页面',
'Static Pages' => '静态页面',
'Site Map Pages' => '站点地图中的页面',
'Set Location' => '设置位置',
'Set Map' => '设置地图',
'Activities' => '活动',
'Back to Gallery' => '回到画廊',
'Back to Galleries' => '回到画廊',
];
